#!/bin/bash

name=$(jq -r '.name' data.json)
height=$(jq -r '.height' data.json)
weight=$(jq -r '.weight' data.json)
type=$(jq -r '.types[0].type.name' data.json)

formatted_height=$(echo "$height" | awk '{printf "%.1f", $1/10}')
formatted_weight=$(echo "$weight" | awk '{printf "%.0f", $1/10}')

name=$(echo "$name" | sed 's/^./\U&/')
type=$(echo "$type" | sed 's/^./\U&/')

echo "$name is of type $type, weighs ${formatted_weight}kg, and is ${formatted_height}m tall."